nmHoistingLimits: workspaces

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

npmScopes:
  rnmf:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.philscott.io"
    npmAuthToken: "${VERDACCIO_AUTH_TOKEN}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
